name: Build & Push Image

permissions:
  contents: write
  
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
      # NOTE: Runner `ubuntu-24.04-arm` not yet supported on private repos.
        platform: [ amd64 , arm64 ]
        include:
          - platform: amd64
            runner: ubuntu-latest
          - platform: arm64
            runner: ubuntu-24.04-arm

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and push image
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
          REPO_OWNER=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
          REPO_NAME=$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          IMAGE_NAME="ghcr.io/${REPO_NAME}"
          echo "IMAGE_NAME=${IMAGE_NAME}:${VERSION}"
          docker buildx build \
            --platform ${{ matrix.platform }} \
            --build-arg VERSION="${VERSION}" \
            -t "${IMAGE_NAME}:${VERSION}" \
            -t "${IMAGE_NAME}:latest" \
            -f Dockerfile \
            --push .